services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb
    ports:
      - "3306"
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_net
    restart: always

  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
      - redis
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception_net
    restart: always

  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/wordpress
      - ./requirements/bonus/static-site:/var/www/static-site
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    depends_on:
      - wordpress
    networks:
      - inception_net
    restart: always

  redis:
    container_name: redis
    image: redis
    build: ./requirements/bonus/redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - inception_net
    restart: always

  ftp:
    container_name: ftp
    build: ./requirements/bonus/ftp
    env_file: .env
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception_net
    restart: always

  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    ports:
      - "8080:8080"
    networks:
      - inception_net
    restart: always

  portainer:
    container_name: portainer
    build: ./requirements/bonus/portainer
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - inception_net
    restart: always

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ducky/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ducky/data/wordpress
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ducky/data/redis
  portainer_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ducky/data/portainer

networks:
  inception_net:
    driver: bridge
